// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXfBRiUO4PcLLdFoQGeqWi_9VcTRToHoY',
    appId: '1:317613197049:web:e55164f0937bc102e8c428',
    messagingSenderId: '317613197049',
    projectId: 'etaxi-f14e9',
    authDomain: 'etaxi-f14e9.firebaseapp.com',
    storageBucket: 'etaxi-f14e9.appspot.com',
    measurementId: 'G-C2TC6SZCDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOeUHSRVFIAuFV98yJlnQfXMh9QYW3csY',
    appId: '1:317613197049:android:9ca25ec7d34ab428e8c428',
    messagingSenderId: '317613197049',
    projectId: 'etaxi-f14e9',
    storageBucket: 'etaxi-f14e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaeRtdSoXKGP_XRN8ps-p05N6Tmc5x5Vs',
    appId: '1:317613197049:ios:8bfc8c142e893569e8c428',
    messagingSenderId: '317613197049',
    projectId: 'etaxi-f14e9',
    storageBucket: 'etaxi-f14e9.appspot.com',
    iosClientId: '317613197049-1ktf6m4uogt3h72v635jb1o3nin941pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.etaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaeRtdSoXKGP_XRN8ps-p05N6Tmc5x5Vs',
    appId: '1:317613197049:ios:8bfc8c142e893569e8c428',
    messagingSenderId: '317613197049',
    projectId: 'etaxi-f14e9',
    storageBucket: 'etaxi-f14e9.appspot.com',
    iosClientId: '317613197049-1ktf6m4uogt3h72v635jb1o3nin941pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.etaxi',
  );
}
